import pandas as pd
import os 
import glob
from tqdm.auto import tqdm


# ---- Global Variables ------------------------------------------------------
embeddings_dir = "My_Data/protein_embeddings(all)/"
output_dir = "My_Data/processed_data_allspecies_final_merge"
os.makedirs(output_dir, exist_ok=True)
model_suffix = "esmc_600m" # Suffix of model that was added to the files
# ----------------------------------------------------------------------------


def consolidate_embeddings(split_name: str) -> None:
    '''
    Takes the feather files generated by ESMC-600M & consolidates them for train, validate, test datasets.
    
    Args:
        split_name (str): Input string of which dataset the code will consolidate.

    Returns:
        None- but output files will be sent to output directory defined above
    '''
    pattern = os.path.join(embeddings_dir, f"{split_name}_chunk_*_{model_suffix}.feather")
    files = sorted(glob.glob(pattern))

    if not files: return

    print(f"🔗 Consolidating {len(files)} chunks for {split_name}...")
    # Load all chuncks and concat
    df = pd.concat([pd.read_feather(f) for f in tqdm(files)], ignore_index=True)

    # Save as one master file
    save_path = os.path.join(output_dir, f"{split_name}_master.parquet")
    df.to_parquet(save_path)
    print(f"✅ Created {save_path} (Shape: {df.shape})")
    del df # Free memory immediately


def build_labels(labels_src: pd.DataFrame, go_columns: list[str]) -> pd.pivot_table:
    '''
    Constructs dataframe w/ all Gene Ontology (GO) terms & other metadata.

    Args:
        labels_src (pd.DataFrame): GO Labels 

        go_columns (List[str]): All the Gene Ontology (GO) terms that describe protein functions

    Returns:
        labels (pd.pivot_table): DataFrame w/ GO terms + metadata

    '''

    meta_cols = ["EntryID", "Sequence", "Length"]
    labels = (
        labels_src[meta_cols + ["term"]]
        .assign(value=1)
        .pivot_table(index=meta_cols, columns="term", values="value", fill_value=0)
        .reset_index()
    )
    labels.columns = [f"GO:{c}" if str(c).isdigit() else c for c in labels.columns]
    return labels.reindex(columns=meta_cols + go_columns, fill_value=0)


def merge_labels_and_embeddings(labels_src: pd.DataFrame, emb_df: pd.DataFrame, go_columns: list[str]) -> pd.DataFrame:
    '''
    Merges ESMC-600M embeddings with the to create one unified dataframe w/ all the data we need. 

    Args:
        labels_src (pd.DataFrame): GO Labels

        emb_df (pd.DataFrame): The 1152-dimensional vector that contains embeddings of a protein 

        go_columns (List[str]): All the Gene Ontology (GO) terms that describe protein functions

    Returns:
        pd.DataFrame that has embeddings + labels merged into one
    '''
    labels = build_labels(labels_src, go_columns)
    embedding_cols = [c for c in emb_df.columns if c.startswith("ME:")]
    embs = emb_df[["EntryID"] + embedding_cols]   # already 1 row/protein -- no groupby-mean needed
    return pd.merge(labels, embs, on="EntryID")



if __name__ == "__main__":
    
    # 1) Consolidate the various embedding files into 1 for train, validation, test datasets
    for s in ["train", "valid", "test"]:
        consolidate_embeddings(s)

    # 2) Load Embeddings- already one row per protein, nothing to deduplicate
    train_emb = pd.read_parquet("My_Data/processed_data_allspecies_final_merge/train_master.parquet")
    valid_emb = pd.read_parquet("My_Data/processed_data_allspecies_final_merge/valid_master.parquet")
    test_emb  = pd.read_parquet("My_Data/processed_data_allspecies_final_merge/test_master.parquet")

    # 3) Load Labels- pulled from the ORIGINAL, non-deduplicated split data, where
    # every GO annotation per protein is still its own row
    train_labels_src = pd.read_parquet("My_Data/mmseq2_processed_data/train_aa_data.parquet")
    valid_labels_src = pd.read_parquet("My_Data/mmseq2_processed_data/valid_aa_data.parquet")
    test_labels_src  = pd.read_parquet("My_Data/mmseq2_processed_data/test_aa_data.parquet")

    # 4) Master GO-term checklist across all three splits
    all_terms = pd.concat([train_labels_src['term'], valid_labels_src['term'], test_labels_src['term']]).unique()
    all_go_cols = [f"GO:{t}" if str(t).isdigit() else t for t in all_terms]
    all_go_cols.sort()

    train_df = merge_labels_and_embeddings(train_labels_src, train_emb, all_go_cols)
    valid_df = merge_labels_and_embeddings(valid_labels_src, valid_emb, all_go_cols)
    test_df  = merge_labels_and_embeddings(test_labels_src, test_emb, all_go_cols)
